language: node_js
node_js:
  - '10'
install: 
  - yarn install 
  - yarn build
os: linux
deploy:
  strategy: git
  local_dir: public
  provider: pages
  token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: gh-pages
  keep_history: true
