language: node_js
node_js:
  - '10'
install: 
  - yarn install 
  - yarn build
deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  on:
    branch: master
  target_branch: gh-pages
  keep_history: true
